# Generated by Django 3.1.4 on 2020-12-10 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('R', 'race'), ('T', 'timerace'), ('P', 'physical'), ('K', 'knowledge')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('car', models.CharField(max_length=64)),
                ('year_of_production', models.CharField(max_length=4)),
                ('driver_name', models.CharField(max_length=32)),
                ('qr', models.CharField(max_length=16)),
                ('photo', models.ImageField(upload_to='images')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=9)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.competition')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crew')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('localization', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=200)),
                ('judge_qr', models.CharField(max_length=16)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organizer')),
            ],
        ),
        migrations.AddField(
            model_name='crew',
            name='event',
            field=models.ForeignKey(on_delete=models.SET(0), to='api.event'),
        ),
        migrations.AddField(
            model_name='competition',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
    ]
