# Generated by Django 3.1.4 on 2020-12-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201210_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
