# Generated by Django 3.1.4 on 2020-12-13 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_score_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='type',
        ),
        migrations.AddField(
            model_name='score',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
        migrations.AlterField(
            model_name='score',
            name='competition',
            field=models.CharField(choices=[('R', 'race'), ('T', 'timerace'), ('P', 'physical'), ('K', 'knowledge')], max_length=1),
        ),
    ]
