# Generated by Django 3.1.4 on 2020-12-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201213_2244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
